all:

	g++ -o xeno main.cpp tutorial.cpp tiles.cpp system.cpp sounds.cpp screenshot.cpp places.cpp parser.cpp options.cpp mt19937int.cpp monster.cpp map.cpp loadsave.cpp level.cpp keyboard.cpp items.cpp hero.cpp global.cpp game.cpp fov.cpp def_mons.cpp def_item.cpp -lncurses
